Remis-MacBook-Pro:Project Remi$ pypy counting_scores_extended.py 
	Loading projections...
	Loading projections...
Loading data...
	Reading main..
	Reading rest..
	Training...
	Scoring...
	In: 37353
	Out: 12647

	Training...
	Scoring...
	In: 19627
	Out: 30373

Time: 3043
Remis-MacBook-Pro:Project Remi$ 
Remis-MacBook-Pro:Project Remi$ pypy counting_scores_extended.py 
	Loading projections...
	Loading projections...
Loading data...
	Reading main..
	Reading rest..
	Training...
	Scoring...
	In: 36108
	Out: 13892

	Training...
	Scoring...
	In: 18306
	Out: 31694

Time: 3551