
3-2 (called 5-2)
Remis-MacBook-Pro:Project Remi$ pypy counting_scores_extended.py 
	Loading projections...
	Loading projections...
Loading data...
	Reading main..
	Reading rest..
	Training...
	Scoring...
	In: 36645
	Out: 13355

	Training...
	Scoring...
	In: 20357
	Out: 29643

Saving results..
	Reading main..
	Reading rest..
Time: 3239

Remis-MacBook-Pro:Project Remi$ pypy counting_scores_extended.py 
	Loading projections...
	Loading projections...
Loading data...
	Reading main..
	Reading rest..
	Training...
	Scoring...
	In: 36208
	Out: 13792

	Training...
	Scoring...
	In: 19907
	Out: 30093

Saving results..
	Reading main..
	Reading rest..
Time: 3839